<a href="https://colab.research.google.com/github/Anaswaraks/Text_Generator_using_LSTM/blob/main/Text_Generator_LSTM_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer

In [ ]:
data = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""

In [ ]:
tokenier = Tokenizer()

In [ ]:
tokenier.fit_on_texts([data])

In [ ]:
tokenier.word_index

{'e': 1,
 'a': 2,
 'i': 3,
 't': 4,
 'o': 5,
 's': 6,
 'n': 7,
 'the': 8,
 'r': 9,
 'h': 10,
 'l': 11,
 'u': 12,
 'c': 13,
 'm': 14,
 'd': 15,
 'you': 16,
 'p': 17,
 'y': 18,
 'to': 19,
 'f': 20,
 'w': 21,
 'b': 22,
 'g': 23,
 'of': 24,
 'is': 25,
 'have': 26,
 'will': 27,
 'can': 28,
 'what': 29,
 'v': 30,
 'course': 31,
 'program': 32,
 'in': 33,
 'for': 34,
 'all': 35,
 'sessions': 36,
 'on': 37,
 'k': 38,
 'be': 39,
 'and': 40,
 'this': 41,
 'if': 42,
 'am': 43,
 'pay': 44,
 'payment': 45,
 '7': 46,
 'make': 47,
 'we': 48,
 'do': 49,
 '1': 50,
 'subscription': 51,
 'where': 52,
 'rs': 53,
 'so': 54,
 'campusx': 55,
 'session': 56,
 'our': 57,
 'paid': 58,
 'join': 59,
 'able': 60,
 'your': 61,
 'website': 62,
 'placement': 63,
 '2': 64,
 'j': 65,
 'fee': 66,
 'data': 67,
 'monthly': 68,
 'month': 69,
 'not': 70,
 'get': 71,
 'yes': 72,
 'once': 73,
 'past': 74,
 'feb': 75,
 'assistance': 76,
 '0': 77,
 'science': 78,
 '5600': 79,
 'are': 80,
 'watch': 81,
 'google': 82,
 'by': 83,


In [ ]:
len(tokenier.word_index)

312

In [ ]:
input_sequence = []
for sentence in data.split('\n'):
  tokenized_sentence = tokenier.texts_to_sequences([sentence])[0]
  print(tokenized_sentence)

  for i in range(1,len(tokenized_sentence)):
    input_sequence.append(tokenized_sentence[:i+1])


[123, 8, 32]
[29, 25, 8, 31, 66, 34, 67, 78, 94, 32, 177, 178]
[8, 31, 124, 2, 68, 51, 125, 52, 16, 26, 19, 47, 68, 95, 24, 53, 96, 69]
[29, 25, 8, 97, 98, 24, 8, 31]
[8, 97, 98, 24, 8, 31, 25, 46, 99, 54, 8, 97, 31, 66, 179, 96, 46, 53, 79, 180]
[29, 25, 8, 126, 24, 8, 94, 32]
[48, 27, 39, 181, 8, 182, 183]
[127, 184]
[127, 185, 34, 67, 78]
[67, 186]
[187, 34, 67, 78]
[188, 34, 189, 100]
[128, 190]
[191, 128]
[192]
[101, 129]
[16, 28, 193, 8, 194, 126, 102, 103, 130, 55, 33, 195, 55, 67, 78, 94, 32, 196]
[27, 131, 100, 40, 132, 39, 2, 104, 24, 41, 32]
[133, 132, 40, 131, 100, 197, 80, 70, 2, 104, 24, 41, 198, 199]
[29, 42, 3, 134, 2, 135, 56, 27, 3, 71, 2, 136, 24, 8, 56]
[72, 35, 57, 36, 80, 200, 54, 137, 42, 16, 134, 2, 56, 16, 28, 201, 202, 40, 81, 8, 136]
[52, 28, 3, 203, 8, 138, 204]
[205, 41, 82, 206, 19, 105, 69, 83, 69, 139, 207, 24, 8, 31, 103, 208, 82, 84, 209, 15, 210, 211, 212, 213, 214]
[29, 25, 8, 139, 98, 24, 35, 8, 135, 36]
[215, 35, 8, 36, 216, 64, 217]
[29, 25, 8, 21

In [ ]:
input_sequence

[[123, 8],
 [123, 8, 32],
 [29, 25],
 [29, 25, 8],
 [29, 25, 8, 31],
 [29, 25, 8, 31, 66],
 [29, 25, 8, 31, 66, 34],
 [29, 25, 8, 31, 66, 34, 67],
 [29, 25, 8, 31, 66, 34, 67, 78],
 [29, 25, 8, 31, 66, 34, 67, 78, 94],
 [29, 25, 8, 31, 66, 34, 67, 78, 94, 32],
 [29, 25, 8, 31, 66, 34, 67, 78, 94, 32, 177],
 [29, 25, 8, 31, 66, 34, 67, 78, 94, 32, 177, 178],
 [8, 31],
 [8, 31, 124],
 [8, 31, 124, 2],
 [8, 31, 124, 2, 68],
 [8, 31, 124, 2, 68, 51],
 [8, 31, 124, 2, 68, 51, 125],
 [8, 31, 124, 2, 68, 51, 125, 52],
 [8, 31, 124, 2, 68, 51, 125, 52, 16],
 [8, 31, 124, 2, 68, 51, 125, 52, 16, 26],
 [8, 31, 124, 2, 68, 51, 125, 52, 16, 26, 19],
 [8, 31, 124, 2, 68, 51, 125, 52, 16, 26, 19, 47],
 [8, 31, 124, 2, 68, 51, 125, 52, 16, 26, 19, 47, 68],
 [8, 31, 124, 2, 68, 51, 125, 52, 16, 26, 19, 47, 68, 95],
 [8, 31, 124, 2, 68, 51, 125, 52, 16, 26, 19, 47, 68, 95, 24],
 [8, 31, 124, 2, 68, 51, 125, 52, 16, 26, 19, 47, 68, 95, 24, 53],
 [8, 31, 124, 2, 68, 51, 125, 52, 16, 26, 19, 47, 68, 95, 2

In [ ]:
max_len = max([len(n) for n in input_sequence])
max_len

57

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

padded_input_seq = pad_sequences(input_sequence,max_len)

In [ ]:
# each seq len == 57 --> we fill the remaining with 0
# the last digit of each seq will be the output
padded_input_seq

array([[  0,   0,   0, ...,   0, 123,   8],
       [  0,   0,   0, ..., 123,   8,  32],
       [  0,   0,   0, ...,   0,  29,  25],
       ...,
       [  0,   0,   0, ..., 308,  37, 309],
       [  0,   0,   0, ...,  37, 309, 310],
       [  0,   0,   0, ..., 309, 310, 311]], dtype=int32)

In [ ]:
x = padded_input_seq[:,:-1]
x

array([[  0,   0,   0, ...,   0,   0, 123],
       [  0,   0,   0, ...,   0, 123,   8],
       [  0,   0,   0, ...,   0,   0,  29],
       ...,
       [  0,   0,   0, ...,   0, 308,  37],
       [  0,   0,   0, ..., 308,  37, 309],
       [  0,   0,   0, ...,  37, 309, 310]], dtype=int32)

In [ ]:
y = padded_input_seq[:,-1]
y

array([  8,  32,  25,   8,  31,  66,  34,  67,  78,  94,  32, 177, 178,
        31, 124,   2,  68,  51, 125,  52,  16,  26,  19,  47,  68,  95,
        24,  53,  96,  69,  25,   8,  97,  98,  24,   8,  31,  97,  98,
        24,   8,  31,  25,  46,  99,  54,   8,  97,  31,  66, 179,  96,
        46,  53,  79, 180,  25,   8, 126,  24,   8,  94,  32,  27,  39,
       181,   8, 182, 183, 184, 185,  34,  67,  78, 186,  34,  67,  78,
        34, 189, 100, 190, 128, 129,  28, 193,   8, 194, 126, 102, 103,
       130,  55,  33, 195,  55,  67,  78,  94,  32, 196, 131, 100,  40,
       132,  39,   2, 104,  24,  41,  32, 132,  40, 131, 100, 197,  80,
        70,   2, 104,  24,  41, 198, 199,  42,   3, 134,   2, 135,  56,
        27,   3,  71,   2, 136,  24,   8,  56,  35,  57,  36,  80, 200,
        54, 137,  42,  16, 134,   2,  56,  16,  28, 201, 202,  40,  81,
         8, 136,  28,   3, 203,   8, 138, 204,  41,  82, 206,  19, 105,
        69,  83,  69, 139, 207,  24,   8,  31, 103, 208,  82,  8

In [ ]:
x.shape

(863, 56)

In [ ]:
y.shape

(863,)

In [ ]:
# one-hot encoding

from tensorflow.keras.utils import to_categorical

y = to_categorical(y,num_classes=313)

In [ ]:
y.shape

(863, 313)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,Input

In [ ]:
model = Sequential([Input(shape=(56,)),
                    Embedding(313,100),
                    LSTM(150),
                    Dense(313, activation='softmax')])

In [ ]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ (None, 56, 100)        │        31,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_2 (LSTM)                   │ (None, 150)            │       150,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 313)            │        47,263 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 229,163 (895.17 KB)

 Trainable params: 229,163 (895.17 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(x,y,epochs=100)

Epoch 1/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 7s 131ms/step - accuracy: 0.0672 - loss: 5.5300
Epoch 2/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 81ms/step - accuracy: 0.0776 - loss: 5.1003
Epoch 3/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - accuracy: 0.0776 - loss: 5.0285
Epoch 4/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 81ms/step - accuracy: 0.0776 - loss: 4.9763
Epoch 5/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 81ms/step - accuracy: 0.0776 - loss: 4.9146
Epoch 6/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 4s 129ms/step - accuracy: 0.0800 - loss: 4.8228
Epoch 7/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - accuracy: 0.1228 - loss: 4.6675
Epoch 8/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - accuracy: 0.1448 - loss: 4.4782
Epoch 9/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 81ms/step - accuracy: 0.1727 - loss: 4.2734
Epoch 10/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/step - accuracy: 0.1900 - loss: 4.0870
Epoch 11/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 4s 130ms/step - accuracy: 0.2155 - loss: 3.8862
Epoch 12/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 2s 80ms/s

In [ ]:
import numpy as np
# prediction

text = 'the'
for i in range(16):
  # tokenize
  token_text = tokenier.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text],maxlen=56)
  # predict
  # here model predict the probability
  position = np.argmax(model.predict(padded_token_text))

  for word,indx in tokenier.word_index.items():
    if indx == position:
      text = text + " " + word
      print(text)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step
the course
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
the course follows
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step
the course follows a
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
the course follows a monthly
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
the course follows a monthly subscription
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
the course follows a monthly subscription model
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
the course follows a monthly subscription model where
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
the course follows a monthly subscription model where you
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
the course follows a monthly subscription model where you have
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step
the course follows a monthly subscription model where you have to
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step
the course follows a monthly subscription model where you have to make
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
the course follows a monthly subscription model where you have